[theme]
primaryColor = "#2196F3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#333333"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
